FROM php:7.3.6-fpm-alpine3.9

RUN apk add --no-cache shadow bash mysql-client

RUN docker-php-ext-install pdo pdo_mysql

WORKDIR /var/www

RUN rm -rf /var/www/html

RUN ln -s public html

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY ./laravel /var/www

COPY ./k8s /var/www/k8s

EXPOSE 9000

ENTRYPOINT ["php-fpm"]
