apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app-service
spec:
  type: NodePort
  ports:
    - port: 9000
      protocol: TCP
      nodePort: 30080
  selector:
    app: app
